{% set name = "filter_illumina_index" %}
{% set version = "1.0.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ed9506f24a4930e89e437b9b0f62402478836ef829a2b92a2f837986c3a7d485" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1
  entry_points:
    - filter_illumina_index = filter_illumina_index.filter_illumina_index:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - setuptools
    - biopython >=1.72
    - python
  run:
    - biopython >=1.72
    - python

test:
  imports:
    - filter_illumina_index
  commands:
    - filter_illumina_index --help

about:
  home: https://github.com/twlee79/filter_illumina_index
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Filter a Illumina FASTQ file based on index sequence
  description: Reads a Illumina FASTQ file and compares the sequence index in the sample number position of the sequence identifier to a supplied sequence index. Entries that match the sequence index are filtered into the filtered file (if any) and entries that don't match are filtered into the unfiltered file (if any). Displays the count of total, filtered and unfiltered reads, as well as the number of mismatches found across all reads.

extra:
  recipe-maintainers:
    - twlee79
