{% set name = "filter_illumina_index" %}
{% set version = "1.0.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "782475ffec4a0841f165894e491ab90c0cb7dbbeb18358265143d99ab5b3d53a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
# to build with local tarball built by setuptools in dist directory, use following url
# use sha256sum to get hash
#  url: ../../dist/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - filter_illumina_index = filter_illumina_index.filter_illumina_index:main
  script: python setup.py install --single-version-externally-managed --record=record.txt
  #noarch: python 
  # uncomment above for noarch build

requirements:
  host:
    - setuptools
    - xopen >=v0.9.0
    - dnaio >=v0.4.1
    - python
  run:
    - xopen >=v0.9.0
    - dnaio >=v0.4.1
    - python

test:
  source_files:
    - filter_illumina_index/tests/data/*.fastq
    - filter_illumina_index/tests/data/*.fastq.gz
    - filter_illumina_index/tests/data/results/*.fastq
    - filter_illumina_index/tests/data/results/*.fastq.gz
    - filter_illumina_index/tests/data/results/*.json
    - filter_illumina_index/tests/tmp/.gitkeep
  imports:
    - filter_illumina_index
    - filter_illumina_index.tests
  commands:
    - filter_illumina_index --help
    - python -m filter_illumina_index.tests.test_filter_illumina_index

about:
  home: https://github.com/twlee79/filter_illumina_index
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Filter a Illumina FASTQ file based on index sequence
  description: > 
    Reads a Illumina FASTQ file and compares the sequence index in the sample 
    number position of the sequence identifier to a supplied sequence index. 
    Entries that match the sequence index are filtered into the filtered file 
    (if any) and entries that don't match are filtered into the unfiltered file 
    (if any). Displays the count of total, filtered and unfiltered reads, as 
    well as the number of mismatches found across all reads. Also supports
    dummy 'passthrough' mode for simply redirecting all reads to filtered file 
    for sequence files lacking barcodes.

extra:
  recipe-maintainers:
    - twlee79
