{% set name = "filter_illumina_index" %}
{% set version = "1.0.2" %}
{% set sha256 = "70faeda8dacfe1161f79823af03f4f1337b4d8a302a49dba33227674defd2461" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - filter_illumina_index = filter_illumina_index.filter_illumina_index:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - biopython
    - python
  run:
    - biopython
    - python

test:
  imports:
    - filter_illumina_index
  commands:
    - filter_illumina_index --help

about:
  home: https://github.com/twlee79/filter_illumina_index
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: 'LICENSE'
  summary: Filter a Illumina FASTQ file based on index sequence

extra:
  recipe-maintainers:
    - twlee79
